version: 1
metadata:
  name: "Travel Planner"
  description: "Demo solution that orchestrates a multi-agent travel concierge with dynamic tooling."
  entrypoint_agent: "travel_receptionist"
catalog:
  tools:
    interactives:
      - web_travel_search:
          label: "Busca Web de Viagens"
          description: "Performs hotel, flight, and experience lookups using the synthetic travel catalogue."
          methods:
            - search_hotels
            - search_flights
            - search_experiences
      - trip_builder:
          label: "Montador de Itinerário"
          description: "Agent-scoped itinerary composer that consolidates search results."
          methods:
            - compile_itinerary
  callbacks:
    - after_model_response:
        - conversation_stream:
            label: "Transcrição da Conversa"
            description: "Builds a transcript with every model response."
  agents:
    - travel_receptionist:
        label: "Recepcionista de Viagens"
        description: |
          Atendente principal que acolhe o viajante, coleta preferencias e coordena
          especialistas para montar um plano completo.
        system_instructions:
          ROLE: Recepcionista de viagens responsavel por orquestrar toda a experiencia do viajante.
          CORE RULES:
            - Colete e valide destino, origem, datas, orcamento, preferencias e dados de contato antes de prosseguir.
            - Mantenha cada conversa isolada usando session_id como chave; nunca reutilize dados de outra sessao.
            - Delegue obrigatoriamente para os sub agentes especialistas apropriados com todas as informacoes coletadas.
            - Em caso de erro de delegacao ou ausencia de retorno, informe o usuario, tente novamente e nao forneca plano preliminar.
        assistant_instructions:
          - |
            Apresente-se como anfitrião da jornada e convide cada especialista (`tourism_specialist`, `hotel_specialist`,
            `flight_specialist`, `itinerary_specialist`) quando chegar o momento adequado. Informe ao viajante quem assumirá a
            conversa e permaneça atento para retomar o diálogo assim que o especialista concluir.
          - |
            Registre imediatamente no estado compartilhado todas as confirmações relevantes usando as chaves `origin`,
            `travel.origin`, `destination`, `travel.destination`, `travel_dates.departure`, `travel_dates.return`,
            `travel.passengers`, `budget.total`, `budget.lodging`, `budget.experiences` e `preferences.interests`.
          - |
            Sempre que delegar, compartilhe destino, origem, datas, orçamento (total e por categoria) e preferências atuais para
            manter os especialistas alinhados. Avise o viajante sobre as perguntas adicionais que eles possam fazer diretamente.
          - |
            Documente no estado os custos, links, justificativas e histórico de chamadas retornados pelos especialistas nas chaves
            `specialists.flight_specialist.result`, `specialists.hotel_specialist.result`,
            `specialists.tourism_specialist.result`, `specialists.flight_specialist.invocations`,
            `specialists.hotel_specialist.invocations` e `specialists.tourism_specialist.invocations`.
          - |
            Acione o `itinerary_specialist` somente quando voos e hospedagem estiverem confirmados para que ele converse com o
            viajante e construa o itinerário final junto a você.
          - |
            Caso um especialista precise de complementos, traduza o pedido em perguntas claras ao viajante, colete as respostas e
            retorne ao especialista explicando o que mudou.
          - |
            Evite acionar `transfer_to_agent` manualmente; use apenas os especialistas declarados no workflow e faça transições
            suaves anunciando quando cada conversa começa e termina.
          - |
            Nunca encerre a sessão antes de apresentar um plano completo, validado com o viajante e com todos os especialistas em
            acordo.
        workflow:
          steps:
            - step_name: collect_profile
              label: "Coletar Perfil do Viajante"
              instructions: |
                Identifique destino, origem, datas (ida e volta), número de viajantes, orçamento total e preferências de viagem.
                Armazene os dados confirmados nas chaves `origin`, `destination`, `travel_dates.departure`,
                `travel_dates.return`, `travel.passengers`, `budget.total` e `preferences.interests`.
                Se algum item estiver faltando, solicite novamente antes de delegar para os agentes especialistas.
              callbacks:
                - after_model_response:
                    - conversation_stream
            - step_name: delegate_flights
              label: "Delegar Busca de Voos"
              instructions: |
                Confirme com o viajante os detalhes finais de rota (origem e destino), datas de ida e volta e quantidade de
                passageiros armazenados no estado. Ao delegar, forneça explicitamente `origin`, `destination`, `departure_date`,
                `return_date`, `passengers` e `budget.total` ao `flight_specialist`. Se o especialista solicitar ajustes,
                normalize o pedido em perguntas claras antes de retomar a conversa com o usuário e atualize o estado antes de reenviar.
              agents:
                - type: agent_transfer
                  label: "Especialista em Voos"
                  agent: flight_specialist
                  when_to_use: "Acione assim que origem, destino e datas estiverem definidos para que o especialista converse com o viajante e proponha rotas dentro do orçamento."
                  input:
                    origin:
                      $state: "origin"
                    destination:
                      $state: "destination"
                    departure_date:
                      $state: "travel_dates.departure"
                    return_date:
                      $state: "travel_dates.return"
                    passengers:
                      $state: "travel.passengers"
                    budget:
                      $state: "budget.total"
              callbacks:
                - after_model_response:
                    - conversation_stream
            - step_name: delegate_hotels
              label: "Delegar Busca de Hospedagem"
              instructions: |
                Depois de receber as opções de voo, valide datas de estadia, número de hóspedes e orçamento destinado à
                hospedagem (`budget.lodging`). Ao delegar, envie `destination`, `check_in`, `check_out`, `guests`, `budget.total`
                e `budget.lodging` para o `hotel_specialist` e registre os resultados antes de prosseguir.
              agents:
                - type: agent_transfer
                  label: "Especialista em Hospedagem"
                  agent: hotel_specialist
                  when_to_use: "Convide após confirmar datas de estadia e orçamento destinado à hospedagem para que o especialista alinhe expectativas diretamente com o viajante."
                  input:
                    destination:
                      $state: "destination"
                    check_in:
                      $state: "travel_dates.departure"
                    check_out:
                      $state: "travel_dates.return"
                    guests:
                      $state: "travel.passengers"
                    total_budget:
                      $state: "budget.total"
                    lodging_budget:
                      $state: "budget.lodging"
              callbacks:
                - after_model_response:
                    - conversation_stream
            - step_name: delegate_experiences
              label: "Delegar Experiências"
              instructions: |
                Valide interesses principais, ritmo desejado e orçamento disponível para lazer (`budget.experiences`). Ao delegar,
                informe `destination`, `travel_dates`, `preferences.interests`, `budget.total` e `budget.experiences` ao
                `tourism_specialist` e aguarde uma resposta estruturada com custos, links e justificativas.
              agents:
                - type: agent_transfer
                  label: "Especialista em Turismo"
                  agent: tourism_specialist
                  when_to_use: "Traga quando o viajante quiser experiências, passeios ou sugestões gastronômicas e esteja pronto para dialogar sobre ritmo e orçamento."
                  input:
                    destination:
                      $state: "destination"
                    departure_date:
                      $state: "travel_dates.departure"
                    return_date:
                      $state: "travel_dates.return"
                    interests:
                      $state: "preferences.interests"
                    total_budget:
                      $state: "budget.total"
                    experiences_budget:
                      $state: "budget.experiences"
              callbacks:
                - after_model_response:
                    - conversation_stream
            - step_name: assemble_plan
              label: "Consolidar Plano Final"
              instructions: |
                Verifique se os resultados de voos, hospedagem e experiências estão presentes em
                `specialists.flight_specialist.result`, `specialists.hotel_specialist.result` e `specialists.tourism_specialist.result`.
                Caso positivo, consolide `destination`, `travel_dates`, `budget` e os retornos dos especialistas antes de delegar
                para o `itinerary_specialist` gerar o plano final. Se algum especialista estiver pendente ou houver lacunas,
                solicite correções ao usuário ou repita a delegação correspondente.
              agents:
                - type: agent_transfer
                  label: "Especialista em Itinerário"
                  agent: itinerary_specialist
                  when_to_use: "Solicite somente após voos e hospedagem definidos para que o especialista sintetize o itinerário completo junto ao viajante."
                  input:
                    destination:
                      $state: "destination"
                    departure_date:
                      $state: "travel_dates.departure"
                    return_date:
                      $state: "travel_dates.return"
                    flights:
                      $state: "specialists.flight_specialist.result"
                    hotels:
                      $state: "specialists.hotel_specialist.result"
                    experiences:
                      $state: "specialists.tourism_specialist.result"
                    budget:
                      $state: "budget"
              callbacks:
                - after_model_response:
                    - conversation_stream
        model_settings:
          model: "gemini-2.5-pro"
    - tourism_specialist:
        label: "Especialista em Turismo"
    - hotel_specialist:
        label: "Especialista em Hospedagem"
    - flight_specialist:
        label: "Especialista em Voos"
    - itinerary_specialist:
        label: "Especialista em Itinerário"
